### ISSUE TITLE
Search fails on common cases

### ISSUE THREAD

**Issue by 0az** [dcao/seascape#7]
In the following cases, search returns non-relevant results:
- `cse8`: Zero results, expected `CSE 8A`/`CSE 8B`.
- `cse 8a`: First result is `LIGN 8`, expected `CSE 8A`.
- `dsc 40`: First result is `DSC 10`, expected `DSC 40`.
- `quar`: Zero results, expected courses with `Quarfoot, David James`.

**Comment by dcao** [comment]
The first and third cases will be fixed in the next commit. The second case already works.

**Comment by dcao** [comment]
All cases fixed with 450284e.
